# Generated by Django 5.1.7 on 2025-08-11 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingrediente", "0002_alter_ingrediente_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ListaItens",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_itens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lista de itens faltantes",
                "verbose_name_plural": "Listas de itens faltantes",
            },
        ),
        migrations.CreateModel(
            name="ListaItensIngrediente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantidade", models.FloatField()),
                ("unidade_medida", models.CharField(max_length=25)),
                (
                    "preco",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "id_ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listas_itens",
                        to="ingrediente.ingrediente",
                    ),
                ),
                (
                    "id_lista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="lista_itens.listaitens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Item da Lista de Itens",
                "verbose_name_plural": "Itens da Lista de Itens",
                "unique_together": {("id_lista", "id_ingrediente")},
            },
        ),
    ]
