# Generated by Django 5.1.7 on 2025-08-11 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingrediente", "0002_alter_ingrediente_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receita",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("titulo", models.CharField(max_length=50)),
                ("descricao", models.CharField(max_length=1500)),
                ("tempo_preparo", models.TimeField()),
                ("dificuldade", models.CharField(max_length=25)),
                ("tipo", models.CharField(max_length=25, null=True)),
                ("restricao_alimentar", models.CharField(max_length=25, null=True)),
                ("imagem", models.URLField(max_length=600, null=True)),
                ("quantidade_visualizacao", models.IntegerField(default=0)),
                (
                    "id_usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receitas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita",
                "verbose_name_plural": "Receitas",
            },
        ),
        migrations.CreateModel(
            name="ReceitaIngrediente",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantidade", models.FloatField()),
                ("unidade_medida", models.CharField(max_length=25)),
                (
                    "id_ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receitas",
                        to="ingrediente.ingrediente",
                    ),
                ),
                (
                    "id_receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientes",
                        to="receita.receita",
                    ),
                ),
            ],
            options={
                "verbose_name": "Receita Ingrediente",
                "verbose_name_plural": "Receitas Ingredientes",
                "unique_together": {("id_receita", "id_ingrediente")},
            },
        ),
    ]
