# Generated by Django 5.1.7 on 2025-09-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receita", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="categoria",
            field=models.CharField(
                blank=True,
                choices=[
                    ("massas", "Massas"),
                    ("carnes", "Carnes"),
                    ("aves", "Aves"),
                    ("peixes_frutos_mar", "Peixes e Frutos do Mar"),
                    ("vegetarianos", "Pratos Vegetarianos"),
                    ("veganos", "Pratos Veganos"),
                    ("sopas_caldos", "Sopas e Caldos"),
                    ("saladas", "Saladas"),
                    ("risotos", "Risotos"),
                    ("pizzas", "Pizzas"),
                    ("lanches_sanduiches", "Lanches e Sanduíches"),
                    ("aperitivos", "Aperitivos"),
                    ("bolos", "Bolos"),
                    ("tortas_doces", "Tortas Doces"),
                    ("tortas_salgadas", "Tortas Salgadas"),
                    ("sobremesas", "Sobremesas"),
                    ("doces_brigadeiros", "Doces e Brigadeiros"),
                    ("paes", "Pães"),
                    ("biscoitos", "Biscoitos"),
                    ("bebidas", "Bebidas"),
                    ("sucos_vitaminas", "Sucos e Vitaminas"),
                    ("molhos_temperos", "Molhos e Temperos"),
                    ("acompanhamentos", "Acompanhamentos"),
                    ("arroz_feijao", "Arroz e Feijão"),
                    ("comida_mineira", "Comida Mineira"),
                    ("comida_italiana", "Comida Italiana"),
                    ("comida_japonesa", "Comida Japonesa"),
                    ("comida_mexicana", "Comida Mexicana"),
                    ("comida_chinesa", "Comida Chinesa"),
                    ("comida_arabe", "Comida Árabe"),
                    ("fit_light", "Fit e Light"),
                    ("sem_gluten", "Sem Glúten"),
                    ("sem_lactose", "Sem Lactose"),
                    ("diabeticos", "Para Diabéticos"),
                    ("infantil", "Comida Infantil"),
                    ("festa_aniversario", "Festa e Aniversário"),
                    ("natal_ano_novo", "Natal e Ano Novo"),
                    ("pascoa", "Páscoa"),
                    ("festa_junina", "Festa Junina"),
                    ("outros", "Outros"),
                ],
                default="outros",
                help_text="Categoria da receita",
                max_length=50,
                null=True,
                verbose_name="Categoria",
            ),
        ),
    ]
