# Generated by Django 5.2.4 on 2025-07-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nome do ingrediente', max_length=50)),
            ],
            options={
                'verbose_name': 'ingrediente',
                'verbose_name_plural': 'Ingredientes',
                'db_table': 'Ingredient',
                'ordering': ['name'],
                'managed': True,
            },
        ),
    ]
