# Generated by Django 5.1.7 on 2025-08-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ingrediente", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingrediente",
            options={
                "managed": True,
                "ordering": ["id"],
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
            },
        ),
        migrations.RenameField(
            model_name="ingrediente",
            old_name="name",
            new_name="nome",
        ),
        migrations.AlterModelTable(
            name="ingrediente",
            table="tab_ingrediente",
        ),
    ]
