# Generated by Django 5.1.7 on 2025-09-05 23:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("receita", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Denuncia",
            fields=[
                (
                    "unique_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID Único",
                    ),
                ),
                (
                    "motivo_denuncia",
                    models.IntegerField(
                        choices=[
                            (1, "Conteúdo inadequado"),
                            (2, "Spam"),
                            (3, "Informações falsas"),
                            (4, "Violação de direitos autorais"),
                            (5, "Conteúdo ofensivo"),
                            (6, "Receita perigosa"),
                            (7, "Outros"),
                        ],
                        verbose_name="Motivo da Denúncia",
                    ),
                ),
                (
                    "detalhamento",
                    models.TextField(
                        blank=True,
                        help_text="Máximo 280 caracteres",
                        max_length=280,
                        null=True,
                        verbose_name="Detalhamento",
                    ),
                ),
                (
                    "data_denuncia",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data da Denúncia"
                    ),
                ),
                (
                    "id_denunciante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias_feitas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Denunciante",
                    ),
                ),
                (
                    "id_receita",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias",
                        to="receita.receita",
                        verbose_name="Receita Denunciada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Denúncia",
                "verbose_name_plural": "Denúncias",
                "ordering": ["-data_denuncia"],
                "unique_together": {("id_receita", "id_denunciante")},
            },
        ),
    ]
